- name: configure catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y        #this doesn't need shell(don't need '|' '>')

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
    
  - name: create system user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true        #--system like in shell
      home: /app          #--home /app
      shell: /sbin/nologin
      comment: "Roboshop system user"

  - name: delete app directory                               
    ansible.builtin.file:
      path: /app
      state: absent 

  - name: create app directory
    ansible.builtin.file:                     ##for linux on a kernal level, everything is a file, directory is just like a path
      path: /app
      state: directory

  - name: delete catalogue zip file          #everyday/ often code changes will happen and devs push it, here we are delteing existing code and downloading new code
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent

  - name: download catalogue     
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: Unarchive catalogue
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app 
      remote_src: yes

  - name: install dependencies
    community.general.npm: 
      path: /app            #(path-> package.json in /app loc)

  - name: copy catalogue service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present

  - name: check products loaded
    ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"   #if stdout less than 0, products yet to load, then load

  - name: load the products
    ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
    when: catalogue_output.stdout  | int < 0

  - name: start catalogue
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes 



























# - name: configure catalogue
#   hosts: catalogue
#   become: yes
#   tasks: 
#   - name: enable nodejs 20
#     ansible.builtin.command: dnf module enable nodejs:20 -y        #this doesn't need shell(don't need '|' '>')
  
#   - name: install nodejs
#     ansible.builtin.dnf:
#       name: nodejs
#       state: present

#   - name: create system user roboshop
#     ansible.builtin.user:
#       name: roboshop
#       system: true
#       home: /app
#       shell: /sbin/nologin
#       comment: "Roboshop system user"

#   - name: create app directory                             
#     ansible.builtin.file:                            #for linux on a kernal level, everything is a file, directory is just like a path
#       path: /app
#       state: directory                                  #collection name is file, if we want to give directory specifically then state: directory


#   - name: download catalogue
#     ansible.builtin.get_url:
#       url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
#       dest: /tmp/catalogue.zip

#   - name: unarchive catalogue
#     ansible.builtin.unarchive:
#       src: /tmp/catalogue.zip
#       dest: /app
#       remote_src: yes                 #File is already present on the target server, Ansible will NOT copy it, It will just extract it