- name: configure catalogue
  hosts: catalogue
  become: yes
  tasks: 
  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y        #this doesn't need shellm(don't need '|' '>')
  
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create system user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"

  - name: create app directory                             
    ansible.builtin.file:                            #for linux on a kernal level, everything is a file, directory is just like a path
    path: /app
    state: directory                                  #collection name is file, if we want to give directory specifically then state: directory


  - name: download catalogue
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: unarchive catalogue
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app