- name: create ec2 and r53 records
  hosts: all
  connection: local
  vars:
  SG_ID: "sg-017b4d9d9d993f2b1"
  IMAGE_ID: "ami-0220d79f3f480ecf5"
  env: dev
  instances:         #if we want few more instances to create then we can override the variable(instances) from command line cuz var. precedence order high for cline than play level vars
  - mongodb
  - catalogue
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{ SG_ID }}"
      image_id: "{{ IMAGE_ID }}"
      #networking and availability zone we are leaving it for default
      name: "{{ item }}-{{ env }}"
      tags: 
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    register: ec2_output         #we wrote to create instance but to create r53, we need to have the instance output(ip and all) for that we use register and keep that output in register


  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

